### ISSUE TITLE
AttributeError: 'module' object has no attribute 'core' with pyzmq 15.2.0

### ISSUE THREAD

**Issue by ice3** [zacharyvoase/zmqc#15]
Hi, 

I installed _zmqc_ with pip

```
sudo pip install zmqc
```

It was installed correctly 

```
zmqc
usage: zmqc [-h] [-v] [-0] [-r | -w] (-b | -c)
            SOCK_TYPE [-o SOCK_OPT=VALUE...]
            address [address ...]
zmqc: error: too few arguments
```

But when using the tool I got the stacktrace : 

```
zmqc -rb SUB 'tcp://127.0.0.1:5557'                    
Traceback (most recent call last):
  File "/usr/local/bin/zmqc", line 11, in <module>
    load_entry_point('zmqc==0.1.0', 'console_scripts', 'zmqc')()
  File "/usr/local/lib/python2.7/dist-packages/zmqc.py", line 286, in main
    sock_opts = get_sockopts(args.sock_opts)
  File "/usr/local/lib/python2.7/dist-packages/zmqc.py", line 227, in get_sockopts
    int: set(zmq.core.constants.int_sockopts).union(
AttributeError: 'module' object has no attribute 'core'
```

---

Here are my zmq / pyzmq and python versions

```
ipython
iPython 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import zmq

In [2]: zmq.zmq_version
Out[2]: <function zmq.sugar.version.zmq_version>

In [3]: zmq.zmq_version()
Out[3]: '4.1.2'

In [4]: zmq.pyzmq_version
Out[4]: <function zmq.sugar.version.pyzmq_version>

In [5]: zmq.pyzmq_version()
Out[5]: '15.2.0'
```

**Comment by vlcinsky** [comment]
zmqc on pypi is very very old and my past attempts to manage publishing updated version failed as I got not permission from zacharyvoase.

If you need functional version, install latest version from github, e.g.

```
$ pip install git+git@github.com:zacharyvoase/zmqc.git#egg=zmqc
```

or using http protocol:

```
pip install git+https://github.com/zacharyvoase/zmqc.git#egg=zmqc
```

I am closing this issue, feel free to reopen it if you get the same issue with latest version.

**Comment by ice3** [comment]
It works. 
Thanks :)
