### ISSUE TITLE
Too old distribute package dependency?

### ISSUE THREAD

**Issue by XVilka** [zacharyvoase/zmqc#17]
```
$ pip3 install --user zmqc
Collecting zmqc
  Using cached zmqc-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.24.tar.gz
    Traceback (most recent call last):
      File "/tmp/pip-build-uh7xyrn8/zmqc/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uh7xyrn8/zmqc/setup.py", line 5, in <module>
        use_setuptools()
      File "/tmp/pip-build-uh7xyrn8/zmqc/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-uh7xyrn8/zmqc/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/tmp/pip-build-uh7xyrn8/zmqc/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uh7xyrn8/zmqc/
```
Same happens with pip for Python 2.

**Comment by vlcinsky** [comment]
Try this pull request, it might solve the issue: https://github.com/zacharyvoase/zmqc/pull/11

I will check this project later on, if I have enough privileges to improve the situation (ideally incl. pushing updated package to pypi - but that effort failed in past).
