### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by XVilka** [zacharyvoase/zmqc#18]
Currently it is incompatible:
```
$ zmqc -rc SUB 'tcp://*:6558'
Traceback (most recent call last):
  File "/home/akochkov/.local/bin/zmqc", line 11, in <module>
    load_entry_point('zmqc==0.1.1', 'console_scripts', 'zmqc')()
  File "/home/akochkov/.local/lib/python3.6/site-packages/zmqc-0.1.1-py3.6.egg/zmqc.py", line 302, in main
  File "zmq/backend/cython/socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4619)
TypeError: unicode not allowed, use setsockopt_string
```
Then I changed line 302 to use `b''` instead of `''` for SUBSCRIBE operation, but got a new error:
```
$ zmqc -rc SUB 'tcp://*:6558'
Traceback (most recent call last):
  File "/home/akochkov/.local/bin/zmqc", line 11, in <module>
    load_entry_point('zmqc==0.1.1', 'console_scripts', 'zmqc')()
  File "/home/akochkov/.local/lib/python3.6/site-packages/zmqc-0.1.1-py3.6.egg/zmqc.py", line 306, in main
  File "zmq/backend/cython/socket.pyx", line 528, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:5980)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:8400)
zmq.error.ZMQError: Invalid argument

**Comment by XVilka** [comment]
Nevermind, 2nd error was related to the missing connection. So just one line change.
